### ISSUE TITLE
Don't require exact node version for deploy

### ISSUE THREAD

**Issue by sandersky** [ciena-blueplanet/pr-bumper#135]
Update `maybe-bump-version.sh` and `maybe-publish-coverage.sh` to work with non-exact Node versions for the deploy part of a Travis config. For example instead of:
```
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8.1.2'
    tags: true
```
I should be able to do:
```
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8'
    tags: true
```
This allows you to write Travis configs that always use the latest minor/patch version for a given major.
